Update script to check all before failing

diff --git a/.github/workflows/upload_docs.yml b/.github/workflows/upload_docs.yml
--- a/.github/workflows/upload_docs.yml
+++ b/.github/workflows/upload_docs.yml
@@ -86,6 +86,7 @@ jobs:
 
       - name: Check for version in pubspec.yaml
         run: |
+          failed=false
           for package_dir in packages/*/; do
             package_name=$(basename "$package_dir")
             pubspec_version=$(cat "$package_dir/pubspec.yaml" | grep "version:" | awk '{print $2}')
@@ -95,11 +96,16 @@ jobs:
 
             
             if [ "$pubspec_version" != "$changelog_version" ]; then
-            echo "❌ Error: The version in the pubspec.yaml does not match the version in the CHANGELOG.md"
-            echo "   Package: $package_name, Version: $pubspec_version, Changelog Version: $changelog_version"
-              exit 1
+              echo "❌ Error: The version in the pubspec.yaml does not match the version in the CHANGELOG.md"
+              echo "   Package: $package_name, Version: $pubspec_version, Changelog Version: $changelog_version"
+              failed=true
             fi
           done
+
+          if [ "$failed" = true ]; then
+            echo "❌ Error: Some version mismatch detected"
+            exit 1
+          fi
 
       - name: Verify CHANGELOGs have been updated
         if: github.event_name == 'pull_request'
